services:
  db:
    image: postgis/postgis:17-3.5
    container_name: hemobridge-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-hemobridge}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?defina POSTGRES_PASSWORD no .env}
      POSTGRES_DB: ${POSTGRES_DB:-hemobridge}
      TZ: America/Sao_Paulo
    ports:
      - '${POSTGRES_PORT:-5434}:5432'
    volumes:
      - hemobridge-pgdata:/var/lib/postgresql/data
      - ./docker/postgres-init/20-remove-extensoes-extras.sql:/docker-entrypoint-initdb.d/20-remove-extensoes-extras.sql:ro
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}']
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  hemobridge-pgdata:
